### ISSUE TITLE
Besoins

### ISSUE THREAD

**Issue by dommangetnicolas** [Leafgard/DynamicProsit#26]
Je sais pas si vous avez des besoins dans vos prosit. Mais pendant le prosit aller il me manquait les besoins...

**Comment by Leafgard** [comment]
C'est prévu ! 😛

**Comment by dommangetnicolas** [comment]
Super 😉

**Comment by Leafgard** [comment]
Je la fermerais quand je l'aurais fait pour pas oublier ^^

**Comment by Leafgard** [comment]
Alors ouai bonjour xD Je vais rework DynamicProsit avec React donc j'en profite pour régler les issues !

Concernant les besoins, ce serait d'après toi une catégorie à part comme les mots-clés ou les contraintes, ou tu verrais ça plutôt comme une sous-catégorie à quelque chose ?

Merci 😄

**Comment by dommangetnicolas** [comment]
Salut,

React est un très bon choix. Honnêtement je ne sais pas te répondre, j'ai quitté le CESI et ai un peu oublié le fonctionnement de Prosit. 

Bonne soirée,
Nicolas.

**Comment by Leafgard** [comment]
Ahh désolé !

Bonne continuation à toi et bonne soirée également,
Yann.
