### ISSUE TITLE
Insertion d'élement html

### ISSUE THREAD

**Issue by Madriax** [Leafgard/DynamicProsit#36]
Je crois qu'il est possible d'insérer des éléments pas très adaptés à un prosit dans les différentes catégories en insérant du code HTML ou Javascript.
![image](https://user-images.githubusercontent.com/23656170/59270994-2d32f800-8c53-11e9-8b92-701bd3590ede.png)

ça ne gène pas dans l'utilisation du programme mais cela ne fait pas pro.

**Comment by Madriax** [comment]
Attention, je viens de remarquer qu'il est possible de fermer la fenêtre avec du code javascript. Mais comme à la réouverture il récupère les anciennes données, impossible de ré-accéder aux mots-clés.
ça gène dans l'utilisation du programme et cela ne fait pas pro !

**Comment by Leafgard** [comment]
En effet, ça va être corrigé ! Merci !
