### ISSUE TITLE
Erreur de génération

### ISSUE THREAD

**Issue by Ratibus11** [Leafgard/DynamicProsit#38]
Au moins par chance il ne plante pas comme certains logiciels ^^
Les prosits sont sauvés !
<img width="532" alt="image" src="https://user-images.githubusercontent.com/49524093/81177906-b065e680-8fa7-11ea-83db-9268409e172b.png">
Mais cela dit la génération a un petit soucis 🧐

**Comment by Leafgard** [comment]
Intéressant.. Tu as fais quoi avant le crash ? Généré le prosit ?

**Comment by Ratibus11** [comment]
Oui exact, en cliquant sur le bouton.
Mais du moins, le logiciel ne crash pas, il refuse simplement de générer 😁

**Comment by Leafgard** [comment]
Je close l'issue vu que je vais refaire toute l'appli.
