### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Madriax** [Leafgard/DynamicProsit#4]
Les boutons du haut (options, réduire, plein écran et fermer) ne sont pas cliquables sous Windows 10.
![image](https://user-images.githubusercontent.com/23656170/50425326-29addf00-0874-11e9-9e0d-ae803de8b4ae.png)

**Comment by Leafgard** [comment]
[Fixed with #9c349ec](https://github.com/Leafgard/DynamicProsit/commit/9c349ec72fb2a8172d1ea7f0dfd344ff23f31523)
